# Generated by Django 4.2.11 on 2024-06-25 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='Без заголовка', max_length=200),
            preserve_default=False,
        ),
    ]
