# Generated by Django 4.2.11 on 2024-06-26 11:04

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=ckeditor.fields.RichTextField(help_text='Текст вашего поста', verbose_name='Текст'),
        ),
    ]
