# Generated by Django 4.2.11 on 2024-06-19 17:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('serials', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookmark',
            options={'verbose_name': 'Избранное', 'verbose_name_plural': 'Избранные сериалы'},
        ),
        migrations.AlterModelOptions(
            name='originaltitle',
            options={'verbose_name': 'Название сериала', 'verbose_name_plural': 'Название сериалов'},
        ),
        migrations.AlterModelOptions(
            name='serialproduct',
            options={'verbose_name': 'Сериал', 'verbose_name_plural': 'Сериалы'},
        ),
        migrations.RenameField(
            model_name='bookmark',
            old_name='movie',
            new_name='serial',
        ),
        migrations.RenameField(
            model_name='ratingserials',
            old_name='movie',
            new_name='serial',
        ),
        migrations.AlterField(
            model_name='originaltitle',
            name='title',
            field=models.CharField(max_length=128, verbose_name='Название сериала'),
        ),
        migrations.AlterField(
            model_name='serialproduct',
            name='descriptions',
            field=models.TextField(default='', max_length=1024, verbose_name='Описание сериала'),
        ),
        migrations.AlterField(
            model_name='serialproduct',
            name='title',
            field=models.CharField(max_length=128, verbose_name='Оригинальное название сериала'),
        ),
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together={('user', 'serial')},
        ),
    ]
