# Generated by Django 4.2.11 on 2024-06-20 16:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('serials', '0002_alter_bookmark_options_alter_originaltitle_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RatingSerials',
            new_name='RatingSerial',
        ),
    ]
