# Generated by Django 4.2.11 on 2024-06-20 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('serials', '0003_rename_ratingserials_ratingserial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingserial',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serials_ratings', to=settings.AUTH_USER_MODEL),
        ),
    ]
