# Generated by Django 3.2.16 on 2024-03-12 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='director',
            options={'verbose_name': 'Режиссёр', 'verbose_name_plural': 'Режиссёры'},
        ),
        migrations.AlterModelOptions(
            name='originaltitle',
            options={'verbose_name': 'Название фильма', 'verbose_name_plural': 'Название фильмов'},
        ),
        migrations.AlterModelOptions(
            name='producttype',
            options={'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанры'},
        ),
        migrations.AlterModelOptions(
            name='videoproduct',
            options={'verbose_name': 'Фильм', 'verbose_name_plural': 'Фильмы'},
        ),
        migrations.AddField(
            model_name='videoproduct',
            name='descriptions',
            field=models.TextField(default='', max_length=256, verbose_name='Описание фильма'),
        ),
        migrations.AlterField(
            model_name='director',
            name='full_name',
            field=models.CharField(max_length=128, verbose_name='Имя режиссёра'),
        ),
        migrations.AlterField(
            model_name='originaltitle',
            name='title',
            field=models.CharField(max_length=128, verbose_name='Название фильма'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='title',
            field=models.CharField(max_length=128, verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='videoproduct',
            name='directors',
            field=models.ManyToManyField(to='cinema.Director', verbose_name='Режиссёры'),
        ),
        migrations.AlterField(
            model_name='videoproduct',
            name='original_title',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cinema.originaltitle', verbose_name='Выберите фильм'),
        ),
        migrations.AlterField(
            model_name='videoproduct',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.producttype', verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='videoproduct',
            name='title',
            field=models.CharField(max_length=128, verbose_name='Название фильма'),
        ),
    ]
