# Generated by Django 3.2.16 on 2024-03-12 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_auto_20240312_2016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoproduct',
            name='product_type',
        ),
        migrations.AddField(
            model_name='videoproduct',
            name='product_type',
            field=models.ManyToManyField(to='cinema.ProductType', verbose_name='Жанр'),
        ),
    ]
