# Generated by Django 3.2.16 on 2024-03-12 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_auto_20240312_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoproduct',
            name='image',
            field=models.ImageField(default='', upload_to='images/pic', verbose_name='Обложка'),
        ),
    ]
