# Generated by Django 3.2.16 on 2024-03-12 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0005_auto_20240312_2240'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actor',
            options={'verbose_name': 'Актёр', 'verbose_name_plural': 'Актёры'},
        ),
        migrations.AlterModelOptions(
            name='release_year',
            options={'verbose_name': 'Год релиза', 'verbose_name_plural': 'Года релизов'},
        ),
        migrations.RemoveField(
            model_name='release_year',
            name='title',
        ),
        migrations.AlterField(
            model_name='actor',
            name='full_name',
            field=models.CharField(max_length=128, verbose_name='Имя актёра'),
        ),
        migrations.AlterField(
            model_name='videoproduct',
            name='actors',
            field=models.ManyToManyField(to='cinema.Actor', verbose_name='Актёры'),
        ),
        migrations.AlterField(
            model_name='videoproduct',
            name='release_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cinema.release_year', verbose_name='Дата выхода'),
        ),
    ]
