# Generated by Django 3.2.16 on 2024-03-12 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0006_auto_20240312_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='release_year',
            name='year',
            field=models.CharField(default='', max_length=4),
        ),
    ]
