# Generated by Django 3.2.16 on 2024-03-12 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0007_release_year_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='release_year',
            name='release_date',
        ),
    ]
