# Generated by Django 3.2.16 on 2024-03-14 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0008_remove_release_year_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoproduct',
            name='descriptions',
            field=models.TextField(default='', max_length=522, verbose_name='Описание фильма'),
        ),
    ]
