# Generated by Django 3.2.16 on 2024-03-14 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0009_alter_videoproduct_descriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoproduct',
            name='descriptions',
            field=models.TextField(default='', max_length=1024, verbose_name='Описание фильма'),
        ),
    ]
